-- MarketSharp Integration Tables
-- Run this migration to set up the tables needed for MarketSharp API sync

-- ─── MarketSharp Contacts Mirror ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS ms_contacts (
  id bigint generated by default as identity primary key,
  marketsharp_id text unique not null,
  first_name text,
  last_name text,
  full_name text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  business_name text,
  source text,
  is_active boolean default true,
  last_synced_at timestamp with time zone default now(),
  ms_created_date text,
  ms_last_update text,
  created_at timestamp with time zone default now()
);

CREATE INDEX IF NOT EXISTS idx_ms_contacts_marketsharp_id ON ms_contacts(marketsharp_id);
CREATE INDEX IF NOT EXISTS idx_ms_contacts_email ON ms_contacts(email);
CREATE INDEX IF NOT EXISTS idx_ms_contacts_name ON ms_contacts(last_name, first_name);

-- ─── MarketSharp Jobs Mirror ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ms_jobs (
  id bigint generated by default as identity primary key,
  marketsharp_id text unique not null,
  marketsharp_contact_id text,
  job_name text,
  description text,
  job_type text,
  status text,
  address text,
  city text,
  state text,
  zip text,
  category text check (category in ('Windows', 'Bathrooms', 'Siding', 'Doors')),
  start_date text,
  sale_date text,
  completed_date text,
  is_active boolean default true,
  last_synced_at timestamp with time zone default now(),
  ms_created_date text,
  ms_last_update text,
  created_at timestamp with time zone default now()
);

CREATE INDEX IF NOT EXISTS idx_ms_jobs_marketsharp_id ON ms_jobs(marketsharp_id);
CREATE INDEX IF NOT EXISTS idx_ms_jobs_contact_id ON ms_jobs(marketsharp_contact_id);
CREATE INDEX IF NOT EXISTS idx_ms_jobs_status ON ms_jobs(status);

-- ─── Link columns on the main jobs table ─────────────────────────────
-- These columns link local jobs to their MarketSharp counterparts
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS marketsharp_job_id text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS marketsharp_contact_id text;
CREATE INDEX IF NOT EXISTS idx_jobs_ms_job_id ON jobs(marketsharp_job_id);

-- ─── Sync Log ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ms_sync_log (
  id bigint generated by default as identity primary key,
  started_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  contacts_synced integer default 0,
  jobs_synced integer default 0,
  errors jsonb,
  status text check (status in ('running', 'success', 'partial', 'failed')) default 'running',
  created_at timestamp with time zone default now()
);

-- ─── RLS Policies ─────────────────────────────────────────────────────
-- Only super admins can view/manage MarketSharp data

ALTER TABLE ms_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ms_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ms_sync_log ENABLE ROW LEVEL SECURITY;

-- ms_contacts policies
CREATE POLICY "Super admins can view MarketSharp contacts" ON ms_contacts
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

CREATE POLICY "Service role can manage MarketSharp contacts" ON ms_contacts
  FOR ALL USING (true)
  WITH CHECK (true);

-- ms_jobs policies
CREATE POLICY "Super admins can view MarketSharp jobs" ON ms_jobs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

CREATE POLICY "Service role can manage MarketSharp jobs" ON ms_jobs
  FOR ALL USING (true)
  WITH CHECK (true);

-- ms_sync_log policies
CREATE POLICY "Super admins can view sync logs" ON ms_sync_log
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

CREATE POLICY "Service role can manage sync logs" ON ms_sync_log
  FOR ALL USING (true)
  WITH CHECK (true);
