-- Part 1: Create tables and insert roles
-- Migration to add role-based access control system
-- This replaces the simple is_super_user boolean with a more flexible role system

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamp with time zone default now(),
  permissions jsonb default '{}' -- Store permissions as JSON for flexibility
);

-- Create user_roles table (global roles for users)
CREATE TABLE IF NOT EXISTS user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role_id bigint references roles not null,
  created_at timestamp with time zone default now(),
  unique(user_id, role_id)
);

-- Create project_user_roles table (project-specific roles)
CREATE TABLE IF NOT EXISTS project_user_roles (
  id bigint generated by default as identity primary key,
  project_id bigint references jobs not null,
  user_id uuid references auth.users not null,
  role_id bigint references roles not null,
  assigned_by uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  unique(project_id, user_id, role_id)
);

-- Enable RLS on new tables
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_user_roles ENABLE ROW LEVEL SECURITY;

-- Insert default roles
INSERT INTO roles (name, description, permissions) VALUES
  ('super_admin', 'Full system access', '{"all": true}'),
  ('brand_ambassador', 'Access to all jobs and photos', '{"jobs": {"read": "all", "write": "all"}, "photos": {"read": "all", "write": "all"}}'),
  ('rep', 'Access to assigned jobs and photos', '{"jobs": {"read": "assigned", "write": "assigned"}, "photos": {"read": "assigned", "write": "assigned"}}'),
  ('measure_tech', 'Access to assigned jobs and jobs they create', '{"jobs": {"read": "assigned_or_created", "write": "assigned_or_created"}, "photos": {"read": "none", "write": "none"}}'),
  ('installer', 'Access to assigned jobs and jobs they create', '{"jobs": {"read": "assigned_or_created", "write": "assigned_or_created"}, "photos": {"read": "none", "write": "none"}}')
ON CONFLICT (name) DO NOTHING;

-- Migrate existing super users to the new system
INSERT INTO user_roles (user_id, role_id)
SELECT p.id, r.id
FROM profiles p
CROSS JOIN roles r
WHERE p.is_super_user = true AND r.name = 'super_admin'
ON CONFLICT (user_id, role_id) DO NOTHING;