-- Migration to add role-based access control system
-- This replaces the simple is_super_user boolean with a more flexible role system

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamp with time zone default now(),
  permissions jsonb default '{}' -- Store permissions as JSON for flexibility
);

-- Create user_roles table (global roles for users)
CREATE TABLE IF NOT EXISTS user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role_id bigint references roles not null,
  created_at timestamp with time zone default now(),
  unique(user_id, role_id)
);

-- Create project_user_roles table (project-specific roles)
CREATE TABLE IF NOT EXISTS project_user_roles (
  id bigint generated by default as identity primary key,
  project_id bigint references jobs not null,
  user_id uuid references auth.users not null,
  role_id bigint references roles not null,
  assigned_by uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  unique(project_id, user_id, role_id)
);

-- Enable RLS on new tables
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_user_roles ENABLE ROW LEVEL SECURITY;

-- Insert default roles
INSERT INTO roles (name, description, permissions) VALUES
  ('super_admin', 'Full system access', '{"all": true}'),
  ('brand_ambassador', 'Access to all jobs and photos', '{"jobs": {"read": "all", "write": "all"}, "photos": {"read": "all", "write": "all"}}'),
  ('rep', 'Access to assigned jobs and photos', '{"jobs": {"read": "assigned", "write": "assigned"}, "photos": {"read": "assigned", "write": "assigned"}}'),
  ('measure_tech', 'Access to assigned jobs and jobs they create', '{"jobs": {"read": "assigned_or_created", "write": "assigned_or_created"}, "photos": {"read": "none", "write": "none"}}'),
  ('installer', 'Access to assigned jobs and jobs they create', '{"jobs": {"read": "assigned_or_created", "write": "assigned_or_created"}, "photos": {"read": "none", "write": "none"}}')
ON CONFLICT (name) DO NOTHING;

-- Migrate existing super users to the new system
INSERT INTO user_roles (user_id, role_id)
SELECT p.id, r.id
FROM profiles p
CROSS JOIN roles r
WHERE p.is_super_user = true AND r.name = 'super_admin'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- RLS Policies for roles table (only super admins can manage roles)
DROP POLICY IF EXISTS "Roles are viewable by authenticated users" ON roles;
CREATE POLICY "Roles are viewable by authenticated users" ON roles
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Only super admins can manage roles" ON roles;
CREATE POLICY "Only super admins can manage roles" ON roles
  FOR ALL USING (
    is_super_admin(auth.uid())
  );

-- RLS Policies for user_roles table
DROP POLICY IF EXISTS "Users can view their own roles" ON user_roles;
CREATE POLICY "Users can view their own roles" ON user_roles
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Super admins can view all user roles" ON user_roles;
CREATE POLICY "Super admins can view all user roles" ON user_roles
  FOR SELECT USING (
    is_super_admin(auth.uid())
  );

DROP POLICY IF EXISTS "Super admins can manage user roles" ON user_roles;
CREATE POLICY "Super admins can manage user roles" ON user_roles
  FOR ALL USING (
    is_super_admin(auth.uid())
  );

-- RLS Policies for project_user_roles table
DROP POLICY IF EXISTS "Users can view project roles they have access to" ON project_user_roles;
CREATE POLICY "Users can view project roles they have access to" ON project_user_roles
  FOR SELECT USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'brand_ambassador'
    )
      OR is_super_admin(auth.uid())
      OR EXISTS (
        SELECT 1 FROM user_roles ur
        JOIN roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'brand_ambassador'
      )
      OR is_super_admin(auth.uid())
    OR EXISTS (
      SELECT 1 FROM jobs j WHERE j.id = project_id AND j.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Authorized users can assign project roles" ON project_user_roles;
CREATE POLICY "Authorized users can assign project roles" ON project_user_roles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'brand_ambassador'
    )
    OR is_super_admin(auth.uid())
    OR EXISTS (
      SELECT 1 FROM jobs j WHERE j.id = project_id AND j.user_id = auth.uid()
    )
  );

-- Update jobs RLS to use new role system
DROP POLICY IF EXISTS "Jobs are viewable by user or super user." ON jobs;
DROP POLICY IF EXISTS "Jobs are viewable based on roles" ON jobs;
CREATE POLICY "Jobs are viewable based on roles" ON jobs
  FOR SELECT USING (
    -- User owns the job
    auth.uid() = user_id
    -- OR user has global role that allows reading all jobs
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.permissions->'jobs'->>'read' = 'all'
    )
    OR is_super_admin(auth.uid())
    -- OR user has project-specific role for this job
    OR EXISTS (
      SELECT 1 FROM project_user_roles pur
      JOIN roles r ON pur.role_id = r.id
      WHERE pur.user_id = auth.uid() AND pur.project_id = jobs.id
      AND r.permissions->'jobs'->>'read' IN ('assigned', 'assigned_or_created')
    )
    -- OR user has global role with 'assigned_or_created' permissions AND is assigned to this job
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      JOIN project_user_roles pur ON pur.user_id = auth.uid()
      WHERE ur.user_id = auth.uid() AND pur.project_id = jobs.id
      AND r.permissions->'jobs'->>'read' = 'assigned_or_created'
    )
    OR is_super_admin(auth.uid())
    )
  );

-- Update job_photos RLS to use new role system
DROP POLICY IF EXISTS "Job photos are viewable by user or super user." ON job_photos;
DROP POLICY IF EXISTS "Job photos are viewable based on roles" ON job_photos;
CREATE POLICY "Job photos are viewable based on roles" ON job_photos
  FOR SELECT USING (
    -- User owns the photo
    auth.uid() = user_id
    -- OR user has global role that allows reading all photos
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.permissions->'photos'->>'read' = 'all'
    )
    OR is_super_admin(auth.uid())
    -- OR user has project-specific role for this job's photos
    OR EXISTS (
      SELECT 1 FROM project_user_roles pur
      JOIN roles r ON pur.role_id = r.id
      JOIN jobs j ON pur.project_id = j.id
      WHERE pur.user_id = auth.uid() AND j.id = job_photos.job_id
      AND r.permissions->'photos'->>'read' = 'assigned'
    )
    OR is_super_admin(auth.uid())
    )
  );

-- Update notes RLS to use new role system
DROP POLICY IF EXISTS "Notes are viewable by users who can access the job." ON notes;
DROP POLICY IF EXISTS "Notes are viewable based on roles" ON notes;
CREATE POLICY "Notes are viewable based on roles" ON notes
  FOR SELECT USING (
    -- User owns the note
    auth.uid() = user_id
    -- OR user has access to the job the note belongs to
    OR EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user has global role that allows reading all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'read' = 'all'
        )
        OR is_super_admin(auth.uid())
        )
        -- OR user has project-specific role for this job
        OR EXISTS (
          SELECT 1 FROM project_user_roles pur
          JOIN roles r ON pur.role_id = r.id
          WHERE pur.user_id = auth.uid() AND pur.project_id = j.id
          AND r.permissions->'jobs'->>'read' IN ('assigned', 'assigned_or_created')
        )
        OR is_super_admin(auth.uid())
        )
      )
    )
  );

-- Update notes INSERT policy
DROP POLICY IF EXISTS "Users can insert notes on jobs they can access." ON notes;
DROP POLICY IF EXISTS "Users can insert notes on accessible jobs" ON notes;
CREATE POLICY "Users can insert notes on accessible jobs" ON notes
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        OR is_super_admin(auth.uid())
        )
        -- OR user has project-specific role for this job
        OR EXISTS (
          SELECT 1 FROM project_user_roles pur
          JOIN roles r ON pur.role_id = r.id
          WHERE pur.user_id = auth.uid() AND pur.project_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
        OR is_super_admin(auth.uid())
        )
      )
    )
  );

-- Update notes UPDATE policy
DROP POLICY IF EXISTS "Users can update notes on jobs they can access." ON notes;
DROP POLICY IF EXISTS "Users can update notes on accessible jobs" ON notes;
CREATE POLICY "Users can update notes on accessible jobs" ON notes
  FOR UPDATE USING (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        OR is_super_admin(auth.uid())
        )
        -- OR user has project-specific role for this job
        OR EXISTS (
          SELECT 1 FROM project_user_roles pur
          JOIN roles r ON pur.role_id = r.id
          WHERE pur.user_id = auth.uid() AND pur.project_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
        OR is_super_admin(auth.uid())
        )
      )
    )
  );

-- Update notes DELETE policy
DROP POLICY IF EXISTS "Users can delete notes on jobs they can access." ON notes;
DROP POLICY IF EXISTS "Users can delete notes on accessible jobs" ON notes;
CREATE POLICY "Users can delete notes on accessible jobs" ON notes
  FOR DELETE USING (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        OR is_super_admin(auth.uid())
        -- OR user has project-specific role for this job
        OR EXISTS (
          SELECT 1 FROM project_user_roles pur
          JOIN roles r ON pur.role_id = r.id
          WHERE pur.user_id = auth.uid() AND pur.project_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
        OR is_super_admin(auth.uid())
      )
    )
  );