-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile entry when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for clients
create table clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text not null,
  address text,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for clients
alter table clients
  enable row level security;

create policy "Clients are viewable by the user who created them." on clients
  for select using (auth.uid() = user_id);

create policy "Users can insert their own clients." on clients
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own clients." on clients
  for update using (auth.uid() = user_id);

create policy "Users can delete their own clients." on clients
  for delete using (auth.uid() = user_id);

-- Create a table for jobs
create table jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  client_id bigint references clients not null,
  description text,
  installation_info text,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for jobs
alter table jobs
  enable row level security;

create policy "Jobs are viewable by the user who created them." on jobs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own jobs." on jobs
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own jobs." on jobs
  for update using (auth.uid() = user_id);

create policy "Users can delete their own jobs." on jobs
  for delete using (auth.uid() = user_id);

-- Create a table for job photos
create table job_photos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  job_id bigint references jobs not null,
  image_url text,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for job_photos
alter table job_photos
  enable row level security;

create policy "Job photos are viewable by the user who created them." on job_photos
  for select using (auth.uid() = user_id);

create policy "Users can insert their own job photos." on job_photos
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own job photos." on job_photos
  for update using (auth.uid() = user_id);

create policy "Users can delete their own job photos." on job_photos
  for delete using (auth.uid() = user_id);

-- Set up Storage for job photos
insert into storage.buckets (id, name)
  values ('job_photos', 'job_photos');

create policy "Job photos are publicly accessible." on storage.objects
  for select using (bucket_id = 'job_photos');

create policy "Anyone can upload a job photo." on storage.objects
  for insert with check (bucket_id = 'job_photos');

-- Create a table for photo tags
create table photo_tags (
  id bigint generated by default as identity primary key,
  photo_id bigint references job_photos not null,
  tag text not null,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for photo_tags
alter table photo_tags
  enable row level security;

create policy "Photo tags are viewable by the user who created them." on photo_tags
  for select using (auth.uid() = user_id);

create policy "Users can insert their own photo tags." on photo_tags
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own photo tags." on photo_tags
  for delete using (auth.uid() = user_id);

-- Create a table for notes
create table notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  job_id bigint references jobs not null,
  photo_id bigint references job_photos,
  content text not null,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for notes
alter table notes
  enable row level security;

create policy "Notes are viewable by the user who created them." on notes
  for select using (auth.uid() = user_id);

create policy "Users can insert their own notes." on notes
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own notes." on notes
  for update using (auth.uid() = user_id);

create policy "Users can delete their own notes." on notes
  for delete using (auth.uid() = user_id);

-- Create a table for team members
create table team_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  email text not null,
  role text default 'member',
  invited_by uuid references auth.users not null,
  user_id uuid references auth.users
);

-- Set up Row Level Security (RLS) for team_members
alter table team_members
  enable row level security;

create policy "Team members are viewable by the user who invited them." on team_members
  for select using (auth.uid() = invited_by);

create policy "Users can invite team members." on team_members
  for insert with check (auth.uid() = invited_by);

-- Add columns to job_photos for better organization
alter table job_photos add column caption text;
alter table job_photos add column photo_type text default 'progress';
-- photo_type can be: 'before', 'after', 'progress', 'issue', 'completed'
alter table job_photos add column latitude double precision;
alter table job_photos add column longitude double precision;
alter table job_photos add column location_accuracy double precision;
