-- Part 1: Migration and table setup
-- Migration: Convert existing project_user_roles to job_assignments
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'project_user_roles') THEN
    INSERT INTO job_assignments (job_id, user_id, assigned_by, created_at)
    SELECT project_id, user_id, assigned_by, created_at
    FROM project_user_roles
    ON CONFLICT (job_id, user_id) DO NOTHING;
  END IF;
END $$;

-- Drop the complex project_user_roles table
DROP TABLE IF EXISTS project_user_roles CASCADE;

-- Create a simple assignments table
CREATE TABLE IF NOT EXISTS job_assignments (
  id bigint generated by default as identity primary key,
  job_id bigint references jobs not null,
  user_id uuid references auth.users not null,
  assigned_by uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  unique(job_id, user_id)
);

-- Enable RLS
ALTER TABLE job_assignments ENABLE ROW LEVEL SECURITY;