-- Simplified role system - remove project-specific roles, just track assignments
-- This replaces the complex project_user_roles table with a simple job_assignments table

-- Migration: Convert existing project_user_roles to job_assignments
-- This will only work if project_user_roles table still exists
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'project_user_roles') THEN
    INSERT INTO job_assignments (job_id, user_id, assigned_by, created_at)
    SELECT project_id, user_id, assigned_by, created_at
    FROM project_user_roles
    ON CONFLICT (job_id, user_id) DO NOTHING;
  END IF;
END $$;

-- Drop the complex project_user_roles table
DROP TABLE IF EXISTS project_user_roles CASCADE;

-- Create a simple assignments table
CREATE TABLE IF NOT EXISTS job_assignments (
  id bigint generated by default as identity primary key,
  job_id bigint references jobs ON DELETE CASCADE not null,
  user_id uuid references auth.users not null,
  assigned_by uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  unique(job_id, user_id)
);

-- Enable RLS
ALTER TABLE job_assignments ENABLE ROW LEVEL SECURITY;

-- Add CASCADE DELETE to existing foreign key constraints
ALTER TABLE job_photos DROP CONSTRAINT IF EXISTS job_photos_job_id_fkey;
ALTER TABLE job_photos ADD CONSTRAINT job_photos_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;

ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_job_id_fkey;
ALTER TABLE notes ADD CONSTRAINT notes_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;

-- Simplified RLS policies for assignments
DROP POLICY IF EXISTS "Users can view assignments they have access to" ON job_assignments;
CREATE POLICY "Users can view assignments they have access to" ON job_assignments
  FOR SELECT USING (
    -- User is assigned to this job
    user_id = auth.uid()
    -- OR user is super_admin
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

DROP POLICY IF EXISTS "Authorized users can manage assignments" ON job_assignments;
CREATE POLICY "Authorized users can manage assignments" ON job_assignments
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

-- Update jobs RLS to use simplified assignment system
DROP POLICY IF EXISTS "Jobs are viewable based on roles" ON jobs;
CREATE POLICY "Jobs are viewable based on roles" ON jobs
  FOR SELECT USING (
    -- User owns the job
    auth.uid() = user_id
    -- OR user is super_admin
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
    -- OR user has global role that allows reading all jobs
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.permissions->'jobs'->>'read' = 'all'
    )
    -- OR user is assigned to this job
    OR EXISTS (
      SELECT 1 FROM job_assignments ja
      WHERE ja.job_id = jobs.id AND ja.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Jobs are updatable by authorized users" ON jobs;
CREATE POLICY "Jobs are updatable by authorized users" ON jobs
  FOR UPDATE USING (
    -- User owns the job
    auth.uid() = user_id
    -- OR user is super_admin
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
    -- OR user has global role that allows writing to all jobs
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.permissions->'jobs'->>'write' = 'all'
    )
  );

DROP POLICY IF EXISTS "Jobs are deletable by super admins" ON jobs;
CREATE POLICY "Jobs are deletable by super admins" ON jobs
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
  );

DROP POLICY IF EXISTS "Jobs are insertable by authorized users" ON jobs;
CREATE POLICY "Jobs are insertable by authorized users" ON jobs
  FOR INSERT WITH CHECK (
    -- User is super_admin
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
    -- OR user has global role that allows writing to all jobs
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.permissions->'jobs'->>'write' = 'all'
    )
  );

-- Update job_photos RLS to use simplified system
DROP POLICY IF EXISTS "Job photos are viewable based on roles" ON job_photos;
CREATE POLICY "Job photos are viewable based on roles" ON job_photos
  FOR SELECT USING (
    -- User owns the photo
    auth.uid() = user_id
    -- OR user is super_admin
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
    )
    -- OR user is brand_ambassador (can see all photos)
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'brand_ambassador'
    )
    -- OR user is rep (can see all photos)
    OR EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'rep'
    )
    -- OR user has access to the job the photo belongs to
    OR EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = job_photos.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user has global role that allows reading all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'read' = 'all'
        )
        -- OR user has global role with 'assigned' permissions AND is assigned to this job
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          JOIN job_assignments ja ON ja.user_id = auth.uid()
          WHERE ur.user_id = auth.uid() AND ja.job_id = j.id
          AND r.permissions->'jobs'->>'read' IN ('assigned', 'assigned_or_created')
        )
      )
    )
  );

-- Update notes RLS to use simplified system
DROP POLICY IF EXISTS "Notes are viewable based on roles" ON notes;
CREATE POLICY "Notes are viewable based on roles" ON notes
  FOR SELECT USING (
    -- User owns the note
    auth.uid() = user_id
    -- OR user has access to the job the note belongs to
    OR EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user is super_admin
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
        )
        -- OR user has global role that allows reading all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'read' = 'all'
        )
        -- OR user has global role with 'assigned' permissions AND is assigned to this job
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          JOIN job_assignments ja ON ja.user_id = auth.uid()
          WHERE ur.user_id = auth.uid() AND ja.job_id = j.id
          AND r.permissions->'jobs'->>'read' IN ('assigned', 'assigned_or_created')
        )
      )
    )
  );

-- Update notes INSERT policy
DROP POLICY IF EXISTS "Users can insert notes on accessible jobs" ON notes;
CREATE POLICY "Users can insert notes on accessible jobs" ON notes
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user is super_admin
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
        )
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        -- OR user has global role with 'assigned' permissions AND is assigned to this job
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          JOIN job_assignments ja ON ja.user_id = auth.uid()
          WHERE ur.user_id = auth.uid() AND ja.job_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
      )
    )
  );

-- Update notes UPDATE policy
DROP POLICY IF EXISTS "Users can update notes on accessible jobs" ON notes;
CREATE POLICY "Users can update notes on accessible jobs" ON notes
  FOR UPDATE USING (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user is super_admin
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
        )
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        -- OR user has global role with 'assigned' permissions AND is assigned to this job
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          JOIN job_assignments ja ON ja.user_id = auth.uid()
          WHERE ur.user_id = auth.uid() AND ja.job_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
      )
    )
  );

-- Update notes DELETE policy
DROP POLICY IF EXISTS "Users can delete notes on accessible jobs" ON notes;
CREATE POLICY "Users can delete notes on accessible jobs" ON notes
  FOR DELETE USING (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.id = notes.job_id
      AND (
        -- User owns the job
        j.user_id = auth.uid()
        -- OR user is super_admin
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
        )
        -- OR user has global role that allows writing to all jobs
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          WHERE ur.user_id = auth.uid()
          AND r.permissions->'jobs'->>'write' = 'all'
        )
        -- OR user has global role with 'assigned' permissions AND is assigned to this job
        OR EXISTS (
          SELECT 1 FROM user_roles ur
          JOIN roles r ON ur.role_id = r.id
          JOIN job_assignments ja ON ja.user_id = auth.uid()
          WHERE ur.user_id = auth.uid() AND ja.job_id = j.id
          AND r.permissions->'jobs'->>'write' IN ('assigned', 'assigned_or_created')
        )
      )
    )
  );